Lambda School Data Science, Unit 2: Predictive Modeling

# Regression & Classification, Module 4


## Assignment

- [ ] Watch Aaron's [video #1](https://www.youtube.com/watch?v=pREaWFli-5I) (12 minutes) & [video #2](https://www.youtube.com/watch?v=bDQgVt4hFgY) (9 minutes) to learn about the mathematics of Logistic Regression.
- [ ] [Sign up for a Kaggle account](https://www.kaggle.com/), if you don’t already have one. Go to our Kaggle InClass competition website. You will be given the URL in Slack. Go to the Rules page. Accept the rules of the competition.
- [ ] Do train/validate/test split with the Tanzania Waterpumps data.
- [ ] Begin with baselines for classification.
- [ ] Use scikit-learn for logistic regression.
- [ ] Get your validation accuracy score.
- [ ] Submit your predictions to our Kaggle competition. (Go to our Kaggle InClass competition webpage. Use the blue **Submit Predictions** button to upload your CSV file. Or you can use the Kaggle API to submit your predictions.)
- [ ] Commit your notebook to your fork of the GitHub repo.

---


## Stretch Goals

- [ ] Add your own stretch goal(s) !
- [ ] Clean the data. For ideas, refer to [The Quartz guide to bad data](https://github.com/Quartz/bad-data-guide),  a "reference to problems seen in real-world data along with suggestions on how to resolve them." One of the issues is ["Zeros replace missing values."](https://github.com/Quartz/bad-data-guide#zeros-replace-missing-values)
- [ ] Make exploratory visualizations.
- [ ] Do one-hot encoding. For example, you could try `quantity`, `basin`, `extraction_type_class`, and more. (But remember it may not work with high cardinality categoricals.)
- [ ] Do [feature scaling](https://scikit-learn.org/stable/modules/preprocessing.html).
- [ ] Get and plot your coefficients.
- [ ] Try [scikit-learn pipelines](https://scikit-learn.org/stable/modules/compose.html).

---

## Data Dictionary 

### Features

Your goal is to predict the operating condition of a waterpoint for each record in the dataset. You are provided the following set of information about the waterpoints:

- `amount_tsh` : Total static head (amount water available to waterpoint)
- `date_recorded` : The date the row was entered
- `funder` : Who funded the well
- `gps_height` : Altitude of the well
- `installer` : Organization that installed the well
- `longitude` : GPS coordinate
- `latitude` : GPS coordinate
- `wpt_name` : Name of the waterpoint if there is one
- `num_private` :  
- `basin` : Geographic water basin
- `subvillage` : Geographic location
- `region` : Geographic location
- `region_code` : Geographic location (coded)
- `district_code` : Geographic location (coded)
- `lga` : Geographic location
- `ward` : Geographic location
- `population` : Population around the well
- `public_meeting` : True/False
- `recorded_by` : Group entering this row of data
- `scheme_management` : Who operates the waterpoint
- `scheme_name` : Who operates the waterpoint
- `permit` : If the waterpoint is permitted
- `construction_year` : Year the waterpoint was constructed
- `extraction_type` : The kind of extraction the waterpoint uses
- `extraction_type_group` : The kind of extraction the waterpoint uses
- `extraction_type_class` : The kind of extraction the waterpoint uses
- `management` : How the waterpoint is managed
- `management_group` : How the waterpoint is managed
- `payment` : What the water costs
- `payment_type` : What the water costs
- `water_quality` : The quality of the water
- `quality_group` : The quality of the water
- `quantity` : The quantity of water
- `quantity_group` : The quantity of water
- `source` : The source of the water
- `source_type` : The source of the water
- `source_class` : The source of the water
- `waterpoint_type` : The kind of waterpoint
- `waterpoint_type_group` : The kind of waterpoint

### Labels

There are three possible values:

- `functional` : the waterpoint is operational and there are no repairs needed
- `functional needs repair` : the waterpoint is operational, but needs repairs
- `non functional` : the waterpoint is not operational

--- 

## Generate a submission

Your code to generate a submission file may look like this:

```python
# estimator is your model or pipeline, which you've fit on X_train

# X_test is your pandas dataframe or numpy array, 
# with the same number of rows, in the same order, as test_features.csv, 
# and the same number of columns, in the same order, as X_train

y_pred = estimator.predict(X_test)


# Makes a dataframe with two columns, id and status_group, 
# and writes to a csv file, without the index

sample_submission = pd.read_csv('sample_submission.csv')
submission = sample_submission.copy()
submission['status_group'] = y_pred
submission.to_csv('your-submission-filename.csv', index=False)
```

If you're working locally, the csv file is saved in the same directory as your notebook.

If you're using Google Colab, you can use this code to download your submission csv file.

```python
from google.colab import files
files.download('your-submission-filename.csv')
```

---

In [24]:
import os, sys
in_colab = 'google.colab' in sys.modules

# If you're in Colab...
if in_colab:
    # Pull files from Github repo
    os.chdir('/content')
    !git init .
    !git remote add origin https://github.com/LambdaSchool/DS-Unit-2-Regression-Classification.git
    !git pull origin master
    
    # Install required python packages
    !pip install -r requirements.txt
    
    # Change into directory for module
    os.chdir('module4')

Reinitialized existing Git repository in /content/.git/
fatal: remote origin already exists.
From https://github.com/LambdaSchool/DS-Unit-2-Regression-Classification
 * branch            master     -> FETCH_HEAD
Already up to date.


In [0]:
# Ignore this Numpy warning when using Plotly Express:
# FutureWarning: Method .ptp is deprecated and will be removed in a future version. Use numpy.ptp instead.
import warnings
warnings.filterwarnings(action='ignore', category=FutureWarning, module='numpy')

In [0]:
# Read the Tanzania Waterpumps data
# train_features.csv : the training set features
# train_labels.csv : the training set labels
# test_features.csv : the test set features
# sample_submission.csv : a sample submission file in the correct format
    
import pandas as pd

train_features = pd.read_csv('../data/waterpumps/train_features.csv')
train_labels = pd.read_csv('../data/waterpumps/train_labels.csv')
test_features = pd.read_csv('../data/waterpumps/test_features.csv')
sample_submission = pd.read_csv('../data/waterpumps/sample_submission.csv')

assert train_features.shape == (59400, 40)
assert train_labels.shape == (59400, 2)
assert test_features.shape == (14358, 40)
assert sample_submission.shape == (14358, 2)

In [0]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LinearRegression
from sklearn.impute import SimpleImputer
import category_encoders as ce
from sklearn.linear_model import LogisticRegressionCV
from sklearn.preprocessing import StandardScaler
from sklearn.feature_selection import f_regression, SelectKBest

In [48]:
train_features.shape, test_features.shape, train_labels.shape

((59400, 40), (14358, 40), (59400, 2))

In [7]:
train_features.select_dtypes(include='number').describe().T

count          mean  ...           75%           max
id                 59400.0  37115.131768  ...  55656.500000  7.424700e+04
amount_tsh         59400.0    317.650385  ...     20.000000  3.500000e+05
gps_height         59400.0    668.297239  ...   1319.250000  2.770000e+03
longitude          59400.0     34.077427  ...     37.178387  4.034519e+01
latitude           59400.0     -5.706033  ...     -3.326156 -2.000000e-08
num_private        59400.0      0.474141  ...      0.000000  1.776000e+03
region_code        59400.0     15.297003  ...     17.000000  9.900000e+01
district_code      59400.0      5.629747  ...      5.000000  8.000000e+01
population         59400.0    179.909983  ...    215.000000  3.050000e+04
construction_year  59400.0   1300.652475  ...   2004.000000  2.013000e+03

[10 rows x 8 columns]

In [8]:
train_features.select_dtypes(exclude='number').describe().T.sort_values(by='unique')

count unique                      top   freq
recorded_by            59400      1  GeoData Consultants Ltd  59400
public_meeting         56066      2                     True  51011
permit                 56344      2                     True  38852
source_class           59400      3              groundwater  45794
management_group       59400      5               user-group  52490
quantity_group         59400      5                   enough  33186
quantity               59400      5                   enough  33186
waterpoint_type_group  59400      6       communal standpipe  34625
quality_group          59400      6                     good  50818
payment_type           59400      7                never pay  25348
source_type            59400      7                   spring  17021
waterpoint_type        59400      7       communal standpipe  28522
extraction_type_class  59400      7                  gravity  26780
payment                59400      7                never pay  25348
water_quality          59400      8                     soft  50818
basin                  59400      9            Lake Victoria  10248
source                 59400     10                   spring  17021
scheme_management      55523     12                      VWC  36793
management             59400     12                      vwc  40507
extraction_type_group  59400     13                  gravity  26780
extraction_type        59400     18                  gravity  26780
region                 59400     21                   Iringa   5294
lga                    59400    125                   Njombe   2503
date_recorded          59400    356               2011-03-15    572
funder                 55765   1897   Government Of Tanzania   9084
ward                   59400   2092                    Igosi    307
installer              55745   2145                      DWE  17402
scheme_name            31234   2696                        K    682
subvillage             59029  19287                 Madukani    508
wpt_name               59400  37400                     none   3563

In [52]:
target = 'status_group'
features = ['population', 'quantity_group', 'water_quality', 'waterpoint_type', 'extraction_type', 'payment_type',
            'public_meeting', 'permit', 'source', 'region_code', 'management_group', 'management',
            'basin', 'longitude', 'latitude']
X_train = mcr_train[features]
y_train = mcr_test[target]
X_val = mcr_val[features]
y_val = mcr_val_test[target]

encoder = ce.OneHotEncoder(use_cat_names=True)
X_train_encoded = encoder.fit_transform(X_train)
X_val_encoded = encoder.transform(X_val)

imputer = SimpleImputer()
X_train_imputed = imputer.fit_transform(X_train_encoded)
X_val_imputed = imputer.transform(X_val_encoded)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train_imputed)
X_val_scaled = scaler.transform(X_val_imputed)

model = LogisticRegressionCV(cv=5, n_jobs=-1, random_state=42)
model.fit(X_train_scaled, y_train)
model.score(X_val_scaled, y_val)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


0.7275420875420875

In [42]:
X_test = test_features[features]
X_test_encoded = encoder.transform(X_test)
X_test_imputed = imputer.transform(X_test_encoded)
X_test_scaled = scaler.transform(X_test_imputed)
y_pred = model.predict(X_test_scaled)

print(y_pred)

['non functional' 'functional' 'non functional' ... 'non functional'
 'functional' 'non functional']


In [0]:
0.7275420875420875

In [0]:
# estimator is your model or pipeline, which you've fit on X_train
 
# X_test is your pandas dataframe or numpy array, 
# with the same number of rows, in the same order, as test_features.csv, 
# and the same number of columns, in the same order, as X_train
 
 y_pred = model.predict(X_test_scaled)
 
# Makes a dataframe with two columns, id and status_group, 
# and writes to a csv file, without the index
 

sample_submission = sample_submission.copy()
sample_submission['status_group'] = y_pred
sample_submission.to_csv('riley_base.csv', index=False)

In [0]:
from google.colab import files
files.download('riley_base.csv')

In [49]:
mcr_train, mcr_val = train_test_split(train_features, random_state=42)
mcr_train.shape, mcr_val.shape

((44550, 40), (14850, 40))

In [50]:
mcr_test, mcr_val_test = train_test_split(train_labels, random_state=42)
mcr_test.shape, mcr_val_test.shape

((44550, 2), (14850, 2))

In [0]:
target = 'status_group'
features = ['amount_tsh', 'population', 'construction_year', 'quantity_group', 'quality_group', 'waterpoint_type', 'extraction_type_class']
X_train = mcr_train[features]
y_train = mcr_test[target]
X_val = mcr_val[features]
y_val = mcr_val_test[target]

encoder = ce.OneHotEncoder(use_cat_names=True)
X_train_encoded = encoder.fit_transform(X_train)
X_val_encoded = encoder.transform(X_val)

imputer = SimpleImputer()
X_train_imputed = imputer.fit_transform(X_train_encoded)
X_val_imputed = imputer.transform(X_val_encoded)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train_imputed)
X_val_scaled = scaler.transform(X_val_imputed)

In [312]:
model = LogisticRegressionCV(cv=5, n_jobs=-1, random_state=42)
model.fit(X_train_scaled, y_train)
model.score(X_val_scaled, y_val)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


0.7006060606060606

In [314]:
X_test = test_features[features]
X_test_encoded = encoder.transform(X_test)
X_test_imputed = imputer.transform(X_test_encoded)
X_test_scaled = scaler.transform(X_test_imputed)
y_pred = model.predict(X_test_scaled)

print(y_pred)

['non functional' 'functional' 'non functional' ... 'functional'
 'functional' 'non functional']


In [325]:
target = 'status_group'
features = ['amount_tsh', 'population', 'construction_year', 'quantity_group', 'quality_group', 'waterpoint_type', 'extraction_type_class', 'payment_type']
X_train = mcr_train[features]
y_train = mcr_test[target]
X_val = mcr_val[features]
y_val = mcr_val_test[target]

encoder = ce.OneHotEncoder(use_cat_names=True)
X_train_encoded = encoder.fit_transform(X_train)
X_val_encoded = encoder.transform(X_val)

imputer = SimpleImputer()
X_train_imputed = imputer.fit_transform(X_train_encoded)
X_val_imputed = imputer.transform(X_val_encoded)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train_imputed)
X_val_scaled = scaler.transform(X_val_imputed)

model = LogisticRegressionCV(cv=5, n_jobs=-1, random_state=42)
model.fit(X_train_scaled, y_train)
model.score(X_val_scaled, y_val)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


0.7096296296296296

In [326]:
target = 'status_group'
features = ['amount_tsh', 'population', 'construction_year', 'quantity_group', 'quality_group', 'waterpoint_type', 'extraction_type_class', 'payment_type', 'public_meeting']
X_train = mcr_train[features]
y_train = mcr_test[target]
X_val = mcr_val[features]
y_val = mcr_val_test[target]

encoder = ce.OneHotEncoder(use_cat_names=True)
X_train_encoded = encoder.fit_transform(X_train)
X_val_encoded = encoder.transform(X_val)

imputer = SimpleImputer()
X_train_imputed = imputer.fit_transform(X_train_encoded)
X_val_imputed = imputer.transform(X_val_encoded)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train_imputed)
X_val_scaled = scaler.transform(X_val_imputed)

model = LogisticRegressionCV(cv=5, n_jobs=-1, random_state=42)
model.fit(X_train_scaled, y_train)
model.score(X_val_scaled, y_val)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


0.7103030303030303

In [0]:
0.7108417508417508

In [0]:
train_features = train_features.replace({'functional': 0, 'non functional': 2, 'functional needs repair': 1})

In [0]:
# Need to one hot encode

In [248]:
mcr_train.describe()

id     amount_tsh  ...    population  construction_year
count  44550.000000   44550.000000  ...  44550.000000       44550.000000
mean   37087.547744     326.361114  ...    178.793333        1303.746083
std    21436.367755    3291.640548  ...    471.050949         950.647840
min        0.000000       0.000000  ...      0.000000           0.000000
25%    18555.250000       0.000000  ...      0.000000           0.000000
50%    36992.500000       0.000000  ...     25.000000        1986.000000
75%    55631.500000      20.000000  ...    211.750000        2004.000000
max    74247.000000  350000.000000  ...  30500.000000        2013.000000

[8 rows x 10 columns]

In [294]:
target = 'status_group'
y_train = mcr_val_test[target]
y_train.value_counts(normalize=True)

functional                 0.545320
non functional             0.382357
functional needs repair    0.072323
Name: status_group, dtype: float64

In [295]:
y_train.mode()[0]

'functional'

In [296]:
majority_class = y_train.mode()[0]
y_pred = [majority_class] * len(y_train)
accuracy_score(y_train, y_pred)

0.5453198653198653

In [297]:
y_val = mcr_val_test[target]
y_pred = [majority_class] * len(y_val)
accuracy_score(y_pred, y_val)

0.5453198653198653

In [253]:
train_features.describe()

id     amount_tsh  ...    population  construction_year
count  59400.000000   59400.000000  ...  59400.000000       59400.000000
mean   37115.131768     317.650385  ...    179.909983        1300.652475
std    21453.128371    2997.574558  ...    471.482176         951.620547
min        0.000000       0.000000  ...      0.000000           0.000000
25%    18519.750000       0.000000  ...      0.000000           0.000000
50%    37061.500000       0.000000  ...     25.000000        1986.000000
75%    55656.500000      20.000000  ...    215.000000        2004.000000
max    74247.000000  350000.000000  ...  30500.000000        2013.000000

[8 rows x 10 columns]

In [0]:
lr = LinearRegression()

features = ['amount_tsh', 'population', 'construction_year']
X_train = mcr_train[features]
X_val = mcr_val[features]

In [0]:
imputer = SimpleImputer()
X_train_imputed = imputer.fit_transform(X_train)
X_val_imputed = imputer.transform(X_val)

In [256]:
X_train_imputed

array([[2.000e+01, 8.000e+01, 1.972e+03],
       [0.000e+00, 0.000e+00, 0.000e+00],
       [0.000e+00, 0.000e+00, 0.000e+00],
       ...,
       [0.000e+00, 1.000e+03, 2.005e+03],
       [0.000e+00, 0.000e+00, 0.000e+00],
       [0.000e+00, 1.000e+00, 1.976e+03]])

In [257]:
y_train.head()

24947    non functional
22630        functional
13789        functional
15697        functional
22613    non functional
Name: status_group, dtype: object

In [258]:
lr.fit(X_train, y_train)

ValueError: ignored

In [136]:
lr.predict(X_val_imputed)

array([0.67097465, 0.67097465, 0.5687297 , ..., 0.57270953, 0.67097465,
       0.57179426])

In [137]:
pd.Series(lr.coef_, features)

amount_tsh          -0.000007
population           0.000011
construction_year   -0.000052
dtype: float64

In [139]:
test_case = [[0, 30500, 2004]]
lr.predict(test_case)

array([0.90610335])

In [146]:
log_reg = LogisticRegression(solver='lbfgs')
log_reg.fit(X_train_imputed, y_train)
print('Validation Accuracy', log_reg.score(X_val_imputed, y_val))

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


Validation Accuracy 0.5453198653198653


In [0]:
0.5453198653198653

In [147]:
log_reg.predict(X_val_imputed)

array([0, 0, 0, ..., 0, 0, 0])

In [148]:
log_reg.predict_proba(X_val_imputed)

array([[0.502361  , 0.40867579, 0.08896321],
       [0.502361  , 0.40867579, 0.08896321],
       [0.5409424 , 0.39567172, 0.06338588],
       ...,
       [0.54221877, 0.39265677, 0.06512445],
       [0.502361  , 0.40867579, 0.08896321],
       [0.54022256, 0.3954902 , 0.06428724]])

In [149]:
log_reg.predict(test_case)

array([0])

In [150]:
log_reg.predict_proba(test_case)

array([[0.53832983, 0.10731287, 0.3543573 ]])

In [152]:
pd.Series(lr.coef_, features)

amount_tsh          -0.000007
population           0.000011
construction_year   -0.000052
dtype: float64

In [153]:
log_reg.intercept_

array([ 1.70262715e-07, -3.77395886e-01, -2.33152998e+00])

In [0]:
import numpy as np

def sigmoid(x):
    return 1 / (1 + np.e**(-x))