Lambda School Data Science

*Unit 2, Sprint 2, Module 2*

---

# Random Forests

## Assignment
- [ ] Read [“Adopting a Hypothesis-Driven Workflow”](http://archive.is/Nu3EI), a blog post by a Lambda DS student about the Tanzania Waterpumps challenge.
- [ ] Continue to participate in our Kaggle challenge.
- [ ] Define a function to wrangle train, validate, and test sets in the same way. Clean outliers and engineer features.
- [ ] Try Ordinal Encoding.
- [ ] Try a Random Forest Classifier.
- [ ] Submit your predictions to our Kaggle competition. (Go to our Kaggle InClass competition webpage. Use the blue **Submit Predictions** button to upload your CSV file. Or you can use the Kaggle API to submit your predictions.)
- [ ] Commit your notebook to your fork of the GitHub repo.

## Stretch Goals

### Doing
- [ ] Add your own stretch goal(s) !
- [ ] Do more exploratory data analysis, data cleaning, feature engineering, and feature selection.
- [ ] Try other [categorical encodings](https://contrib.scikit-learn.org/category_encoders/).
- [ ] Get and plot your feature importances.
- [ ] Make visualizations and share on Slack.

### Reading

Top recommendations in _**bold italic:**_

#### Decision Trees
- A Visual Introduction to Machine Learning, [Part 1: A Decision Tree](http://www.r2d3.us/visual-intro-to-machine-learning-part-1/),  and _**[Part 2: Bias and Variance](http://www.r2d3.us/visual-intro-to-machine-learning-part-2/)**_
- [Decision Trees: Advantages & Disadvantages](https://christophm.github.io/interpretable-ml-book/tree.html#advantages-2)
- [How a Russian mathematician constructed a decision tree — by hand — to solve a medical problem](http://fastml.com/how-a-russian-mathematician-constructed-a-decision-tree-by-hand-to-solve-a-medical-problem/)
- [How decision trees work](https://brohrer.github.io/how_decision_trees_work.html)
- [Let’s Write a Decision Tree Classifier from Scratch](https://www.youtube.com/watch?v=LDRbO9a6XPU)

#### Random Forests
- [_An Introduction to Statistical Learning_](http://www-bcf.usc.edu/~gareth/ISL/), Chapter 8: Tree-Based Methods
- [Coloring with Random Forests](http://structuringtheunstructured.blogspot.com/2017/11/coloring-with-random-forests.html)
- _**[Random Forests for Complete Beginners: The definitive guide to Random Forests and Decision Trees](https://victorzhou.com/blog/intro-to-random-forests/)**_

#### Categorical encoding for trees
- [Are categorical variables getting lost in your random forests?](https://roamanalytics.com/2016/10/28/are-categorical-variables-getting-lost-in-your-random-forests/)
- [Beyond One-Hot: An Exploration of Categorical Variables](http://www.willmcginnis.com/2015/11/29/beyond-one-hot-an-exploration-of-categorical-variables/)
- _**[Categorical Features and Encoding in Decision Trees](https://medium.com/data-design/visiting-categorical-features-and-encoding-in-decision-trees-53400fa65931)**_
- _**[Coursera — How to Win a Data Science Competition: Learn from Top Kagglers — Concept of mean encoding](https://www.coursera.org/lecture/competitive-data-science/concept-of-mean-encoding-b5Gxv)**_
- [Mean (likelihood) encodings: a comprehensive study](https://www.kaggle.com/vprokopev/mean-likelihood-encodings-a-comprehensive-study)
- [The Mechanics of Machine Learning, Chapter 6: Categorically Speaking](https://mlbook.explained.ai/catvars.html)

#### Imposter Syndrome
- [Effort Shock and Reward Shock (How The Karate Kid Ruined The Modern World)](http://www.tempobook.com/2014/07/09/effort-shock-and-reward-shock/)
- [How to manage impostor syndrome in data science](https://towardsdatascience.com/how-to-manage-impostor-syndrome-in-data-science-ad814809f068)
- ["I am not a real data scientist"](https://brohrer.github.io/imposter_syndrome.html)
- _**[Imposter Syndrome in Data Science](https://caitlinhudon.com/2018/01/19/imposter-syndrome-in-data-science/)**_


### More Categorical Encodings

**1.** The article **[Categorical Features and Encoding in Decision Trees](https://medium.com/data-design/visiting-categorical-features-and-encoding-in-decision-trees-53400fa65931)** mentions 4 encodings:

- **"Categorical Encoding":** This means using the raw categorical values as-is, not encoded. Scikit-learn doesn't support this, but some tree algorithm implementations do. For example, [Catboost](https://catboost.ai/), or R's [rpart](https://cran.r-project.org/web/packages/rpart/index.html) package.
- **Numeric Encoding:** Synonymous with Label Encoding, or "Ordinal" Encoding with random order. We can use [category_encoders.OrdinalEncoder](https://contrib.scikit-learn.org/category_encoders/ordinal.html).
- **One-Hot Encoding:** We can use [category_encoders.OneHotEncoder](https://contrib.scikit-learn.org/category_encoders/onehot.html).
- **Binary Encoding:** We can use [category_encoders.BinaryEncoder](https://contrib.scikit-learn.org/category_encoders/binary.html).


**2.** The short video 
**[Coursera — How to Win a Data Science Competition: Learn from Top Kagglers — Concept of mean encoding](https://www.coursera.org/lecture/competitive-data-science/concept-of-mean-encoding-b5Gxv)** introduces an interesting idea: use both X _and_ y to encode categoricals.

Category Encoders has multiple implementations of this general concept:

- [CatBoost Encoder](https://contrib.scikit-learn.org/category_encoders/catboost.html)
- [Generalized Linear Mixed Model Encoder](https://contrib.scikit-learn.org/category_encoders/glmm.html)
- [James-Stein Encoder](https://contrib.scikit-learn.org/category_encoders/jamesstein.html)
- [Leave One Out](https://contrib.scikit-learn.org/category_encoders/leaveoneout.html)
- [M-estimate](https://contrib.scikit-learn.org/category_encoders/mestimate.html)
- [Target Encoder](https://contrib.scikit-learn.org/category_encoders/targetencoder.html)
- [Weight of Evidence](https://contrib.scikit-learn.org/category_encoders/woe.html)

Category Encoder's mean encoding implementations work for regression problems or binary classification problems. 

For multi-class classification problems, you will need to temporarily reformulate it as binary classification. For example:

```python
encoder = ce.TargetEncoder(min_samples_leaf=..., smoothing=...) # Both parameters > 1 to avoid overfitting
X_train_encoded = encoder.fit_transform(X_train, y_train=='functional')
X_val_encoded = encoder.transform(X_train, y_val=='functional')
```

For this reason, mean encoding won't work well within pipelines for multi-class classification problems.

**3.** The **[dirty_cat](https://dirty-cat.github.io/stable/)** library has a Target Encoder implementation that works with multi-class classification.

```python
 dirty_cat.TargetEncoder(clf_type='multiclass-clf')
```
It also implements an interesting idea called ["Similarity Encoder" for dirty categories](https://www.slideshare.net/GaelVaroquaux/machine-learning-on-non-curated-data-154905090).

However, it seems like dirty_cat doesn't handle missing values or unknown categories as well as category_encoders does. And you may need to use it with one column at a time, instead of with your whole dataframe.

**4. [Embeddings](https://www.kaggle.com/colinmorris/embedding-layers)** can work well with sparse / high cardinality categoricals.

_**I hope it’s not too frustrating or confusing that there’s not one “canonical” way to encode categoricals. It’s an active area of research and experimentation — maybe you can make your own contributions!**_

### Setup

You can work locally (follow the [local setup instructions](https://lambdaschool.github.io/ds/unit2/local/)) or on Colab (run the code cell below).

In [1]:
%%capture
import sys
#Hadi was here

# If you're on Colab:
if 'google.colab' in sys.modules:
    DATA_PATH = 'https://raw.githubusercontent.com/LambdaSchool/DS-Unit-2-Kaggle-Challenge/master/data/'
    !pip install category_encoders==2.*

# If you're working locally:
else:
    DATA_PATH = '../data/'

In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split

train = pd.merge(pd.read_csv(DATA_PATH+'waterpumps/train_features.csv'), 
                 pd.read_csv(DATA_PATH+'waterpumps/train_labels.csv'))
test = pd.read_csv(DATA_PATH+'waterpumps/test_features.csv')
sample_submission = pd.read_csv(DATA_PATH+'waterpumps/sample_submission.csv')

train.shape, test.shape

((59400, 41), (14358, 40))

In [3]:
# All imports go here

import numpy as np

from sklearn.feature_selection import SelectKBest, chi2
from sklearn.preprocessing import OrdinalEncoder
from sklearn.impute import SimpleImputer

from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestClassifier


In [4]:
print(train['status_group'].value_counts())
train.head()

functional                 32259
non functional             22824
functional needs repair     4317
Name: status_group, dtype: int64


id  amount_tsh  ... waterpoint_type_group    status_group
0  69572      6000.0  ...    communal standpipe      functional
1   8776         0.0  ...    communal standpipe      functional
2  34310        25.0  ...    communal standpipe      functional
3  67743         0.0  ...    communal standpipe  non functional
4  19728         0.0  ...    communal standpipe      functional

[5 rows x 41 columns]

In [5]:
train.isna().sum()

id                           0
amount_tsh                   0
date_recorded                0
funder                    3635
gps_height                   0
installer                 3655
longitude                    0
latitude                     0
wpt_name                     0
num_private                  0
basin                        0
subvillage                 371
region                       0
region_code                  0
district_code                0
lga                          0
ward                         0
population                   0
public_meeting            3334
recorded_by                  0
scheme_management         3877
scheme_name              28166
permit                    3056
construction_year            0
extraction_type              0
extraction_type_group        0
extraction_type_class        0
management                   0
management_group             0
payment                      0
payment_type                 0
water_quality                0
quality_

In [6]:
# columns to drop during preprocessing
drop_list = ['scheme_name', 'id', 'management', 'management_group',
             'payment', 'payment_type', 'lga', 'permit', 'quantity',
             'water_quality', 'source', 'source_type', 'waterpoint_type',
             'recorded_by', 'region', 'subvillage', 'wpt_name', 'installer',
             'funder', 'date_recorded', 'num_private', 'status_group']

In [7]:
# instantiate preprocessing functions here
# and create preprocessing pipeline

imputer = SimpleImputer(missing_values=np.NaN, strategy='most_frequent')
ord_enc = OrdinalEncoder()

pre_pipe = Pipeline(steps=[('imputer', imputer),
                            ('ord_enc', ord_enc)])

In [8]:
# function to run all datasets through for preprocessing
def prep_data(df, drop_list, pre_pipe, target=None, train=True, predict=False):

    if train is True & predict is True:
        raise ValueError("Variables 'train' and 'target' cannot both be 'True'.")

    # copy dataframe to avoid issues working
    # with pandas
    df = df.copy()

    # create target and apply preprocessing pipeline
    if target is None:
        print('Prediction Mode')
    elif train == True and predict == False:
        target = pre_pipe.fit_transform(target, y=None)
    elif train == False & predict == False:
        target = pre_pipe.transform(target)
    
    # impute missing values
    # drop columns by list, which includes the target
    if train is True:
        df.drop(['date_recorded','status_group'], axis=1, inplace=True)
        trans_data = pre_pipe.fit_transform(df, y=None)

    else:
        df.drop(['date_recorded'], axis=1, inplace=True)
        trans_data = pre_pipe.fit_transform(df)

    
    if target is None:
        return df, trans_data
    else:
        return df, trans_data, target

In [9]:
train_pre, trans_data, target = prep_data(df=train,
                                          drop_list=drop_list,
                                          pre_pipe=pre_pipe,
                                          target=train.loc[ : , ['status_group']])

In [10]:
train_pre.head()

id  amount_tsh  ...              waterpoint_type  waterpoint_type_group
0  69572      6000.0  ...           communal standpipe     communal standpipe
1   8776         0.0  ...           communal standpipe     communal standpipe
2  34310        25.0  ...  communal standpipe multiple     communal standpipe
3  67743         0.0  ...  communal standpipe multiple     communal standpipe
4  19728         0.0  ...           communal standpipe     communal standpipe

[5 rows x 39 columns]

In [11]:
trans_data[:5]

array([[5.5621e+04, 6.2000e+01, 1.3690e+03, 1.4480e+03, 1.5180e+03,
        2.8151e+04, 5.5130e+03, 3.7399e+04, 0.0000e+00, 1.0000e+00,
        1.1807e+04, 3.0000e+00, 1.0000e+01, 5.0000e+00, 5.1000e+01,
        1.4260e+03, 1.0900e+02, 1.0000e+00, 0.0000e+00, 7.0000e+00,
        2.2450e+03, 0.0000e+00, 4.0000e+01, 3.0000e+00, 1.0000e+00,
        0.0000e+00, 7.0000e+00, 4.0000e+00, 2.0000e+00, 0.0000e+00,
        6.0000e+00, 2.0000e+00, 1.0000e+00, 1.0000e+00, 8.0000e+00,
        6.0000e+00, 0.0000e+00, 1.0000e+00, 1.0000e+00],
       [7.0210e+03, 0.0000e+00, 4.6900e+02, 1.4570e+03, 5.4500e+02,
        2.5572e+04, 5.3251e+04, 3.7195e+04, 0.0000e+00, 4.0000e+00,
        1.5838e+04, 9.0000e+00, 1.9000e+01, 2.0000e+00, 1.0300e+02,
        1.5760e+03, 2.7600e+02, 1.0000e+00, 0.0000e+00, 2.0000e+00,
        5.9800e+02, 1.0000e+00, 5.1000e+01, 3.0000e+00, 1.0000e+00,
        0.0000e+00, 1.1000e+01, 4.0000e+00, 0.0000e+00, 2.0000e+00,
        6.0000e+00, 2.0000e+00, 2.0000e+00, 2.0000e+00, 5.0

In [12]:
target

array([[0.],
       [0.],
       [0.],
       ...,
       [0.],
       [0.],
       [0.]])

In [13]:
forest = RandomForestClassifier(n_estimators=100, criterion='gini', min_samples_leaf=20, min_samples_split=40)
kbest_chi2 = SelectKBest(score_func=chi2, k=25)

In [14]:
f_sel = kbest_chi2.fit_transform(trans_data, target)

In [15]:
f_sel

array([[5.5621e+04, 6.2000e+01, 1.3690e+03, ..., 1.0000e+00, 1.0000e+00,
        1.0000e+00],
       [7.0210e+03, 0.0000e+00, 4.6900e+02, ..., 2.0000e+00, 1.0000e+00,
        1.0000e+00],
       [2.7491e+04, 1.3000e+01, 8.2500e+02, ..., 1.0000e+00, 2.0000e+00,
        1.0000e+00],
       ...,
       [2.9696e+04, 0.0000e+00, 4.5600e+02, ..., 1.0000e+00, 4.0000e+00,
        3.0000e+00],
       [2.5101e+04, 0.0000e+00, 8.8400e+02, ..., 2.0000e+00, 4.0000e+00,
        3.0000e+00],
       [2.1127e+04, 0.0000e+00, 1.8650e+03, ..., 1.0000e+00, 4.0000e+00,
        3.0000e+00]])

In [16]:
X_train, X_test, y_train, y_test = train_test_split(f_sel, target)

In [17]:
[print(i.shape,'\n') for i in [X_train, y_train, X_test, y_test]]

(44550, 25) 

(44550, 1) 

(14850, 25) 

(14850, 1) 



[None, None, None, None]

In [18]:
forest.fit(X_train, y_train)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  """Entry point for launching an IPython kernel.


RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=20, min_samples_split=40,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [19]:
forest.score(X_train, y_train)

0.8125028058361392

In [20]:
forest.score(X_test, y_test)

0.7856565656565656

In [21]:
test.head()

id  amount_tsh  ...     waterpoint_type waterpoint_type_group
0  50785         0.0  ...               other                 other
1  51630         0.0  ...  communal standpipe    communal standpipe
2  17168         0.0  ...               other                 other
3  45559         0.0  ...               other                 other
4  49871       500.0  ...  communal standpipe    communal standpipe

[5 rows x 40 columns]

In [22]:
test_clean, trans_val = prep_data(df=test,
                       drop_list=['date_recorded'],
                       pre_pipe=pre_pipe,
                       train=False,
                       predict=True)

Prediction Mode


In [23]:
v_sel = kbest_chi2.transform(trans_val)

In [24]:
y_pred = forest.predict(v_sel)

In [25]:
y_pred

array([2., 0., 2., ..., 0., 0., 2.])

In [26]:
y_pred.shape

(14358,)

In [27]:
test['status_group'] = y_pred
upload = test[['id', 'status_group']]

In [28]:
upload['status_group'].value_counts()

0.0    10631
2.0     3647
1.0       80
Name: status_group, dtype: int64

In [29]:
upload.replace(to_replace=0, value='non functional', inplace=True)
upload.replace(to_replace=1, value='functional needs repair', inplace=True)
upload.replace(to_replace=2, value='functional', inplace=True)

/usr/local/lib/python3.6/dist-packages/pandas/core/frame.py:4384: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  method=method,


In [30]:
upload.to_csv('Kaggle_Submission_Caldwell_James_TL_Hadi.csv', index=False, header=['id', 'status_group'])

In [31]:
pd.read_csv('Kaggle_Submission_Caldwell_James_TL_Hadi.csv')

id    status_group
0      50785      functional
1      51630  non functional
2      17168      functional
3      45559      functional
4      49871  non functional
...      ...             ...
14353  39307      functional
14354  18990  non functional
14355  28749  non functional
14356  33492  non functional
14357  68707      functional

[14358 rows x 2 columns]